build: add -O2 for _FORTIFY_SOURCE
Fix error while compiling:

	/usr/include/features.h:331:4: error: #warning _FORTIFY_SOURCE requires
	compiling with optimization (-O) [-Werror=cpp]
	 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
	     ^~~~~~~